I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/gb_route.rpy", line 48, in script
    rando "Right, but makeup is for girls, Matteo"
Exception: Sayer 'rando' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/gb_route.rpy", line 48, in script
    rando "Right, but makeup is for girls, Matteo"
  File "C:\Users\Laptop\Documents\CREATIVE\Mängude tegemine\renpy-8.1.3-sdk\renpy\ast.py", line 890, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\Laptop\Documents\CREATIVE\Mängude tegemine\renpy-8.1.3-sdk\renpy\ast.py", line 783, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'rando' is not defined.

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.3.23091805
cosocode_gamejam 1.0
Sat Nov  4 14:09:29 2023
